<a href="https://colab.research.google.com/github/007arjungangwar/Foundations-of-Data-Engineering-Sec2/blob/main/Data_Preprocessing_using_pandas_31_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

series=pd.Series([78, 85, 65, 90])
series

0    78
1    85
2    65
3    90
dtype: int64

In [ ]:
print(series.mean())

79.5

In [ ]:
print(series.max())

90

In [ ]:
print(series.min())

65

In [ ]:
print(series.std())

10.847426730181986

In [ ]:
print(round(series.std(),2))

10.85

# **isin**

In [ ]:
series=pd.Series([78, 85, 65, 90])

In [ ]:
series.isin([90])

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
series.isin([65,90])

0    False
1    False
2     True
3     True
dtype: bool

In [ ]:
series[series.isin([65,90])]

2    65
3    90
dtype: int64

In [ ]:
data = {"Name": ["Aarav", "Diya", "Rahul"],
        "Marks": [85, 80, 70]}

df = pd.DataFrame(data)
df

    Name  Marks
0  Aarav     85
1   Diya     80
2  Rahul     70

In [ ]:
df["Marks"].mean()

np.float64(78.33333333333333)

In [ ]:
df["Marks"]>df["Marks"].mean()

0     True
1     True
2    False
Name: Marks, dtype: bool

In [ ]:
df[df["Marks"]>df["Marks"].mean()]

    Name  Marks
0  Aarav     85
1   Diya     80

In [ ]:
df[df["Marks"]==df["Marks"].max()]

    Name  Marks
0  Aarav     85

In [ ]:
df[df["Marks"]==df["Marks"].min()]

    Name  Marks
2  Rahul     70

In [ ]:
data = {"Name": ["Gold", "Silver", "Copper"],
        "Price": [" $85k", "$80k ", " $70k "]}

df1 = pd.DataFrame(data)
df1

     Name   Price
0    Gold    $85k
1  Silver   $80k
2  Copper   $70k

# **strip() , replace()**

In [ ]:
df1["Price"]

0      $85k
1     $80k
2     $70k
Name: Price, dtype: str

In [ ]:
df1["Price"].str.strip()

0    $85k
1    $80k
2    $70k
Name: Price, dtype: str

In [ ]:
df1["U_Price"]=df1["Price"].str.strip()

In [ ]:
df1

     Name   Price U_Price
0    Gold    $85k    $85k
1  Silver   $80k     $80k
2  Copper   $70k     $70k

In [ ]:
df1["Price"]=df1["Price"].str.strip()

In [ ]:
df1["Price"]=df1["Price"].str.strip("$")

In [ ]:
df1

     Name Price U_Price
0    Gold   85k    $85k
1  Silver   80k    $80k
2  Copper   70k    $70k

In [ ]:
df1["Price"]=df1["Price"].str.strip("k")

In [ ]:
df1

     Name Price U_Price
0    Gold    85    $85k
1  Silver    80    $80k
2  Copper    70    $70k

replace

In [ ]:
data = {"Name": ["Gold", "Silver", "Copper"],
        "Price": ["$85k ", " $80k", " $70k "]}

df1 = pd.DataFrame(data)
df1

     Name   Price
0    Gold   $85k
1  Silver    $80k
2  Copper   $70k

In [ ]:
df1['Price']

0     $85k
1      $80k
2     $70k
Name: Price, dtype: str

In [ ]:
df1['Price']=df1['Price'].str.replace("$","").str.replace("k","").str.strip()

In [ ]:
df1

     Name Price
0    Gold    85
1  Silver    80
2  Copper    70

In [ ]:
data = {"Name": ["Gold", "Silver", "Copper"],
        "Price": ["$85k ", " $80k", " $70k "]}

df1 = pd.DataFrame(data)
df1

     Name   Price
0    Gold   $85k
1  Silver    $80k
2  Copper   $70k

In [ ]:
df1['Price'].str.replace({"$":"","k":""}).str.strip()

0    85
1    80
2    70
Name: Price, dtype: str

In [ ]:
df1['Price'].str.replace({"$":"","k":""}).str.strip().astype("int")

0    85
1    80
2    70
Name: Price, dtype: int64

# **New DataSet**

In [ ]:
data_dict = {
    "Name": [
        "Aarav", "Diya", "Rahul", "Priya", "Arjun", "Sneha",
        "Karan", "Ananya", "Vikram", "Meera", "Rohan", "Isha"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male", "Female"
    ],
    "Age": [20, 21, 20, 22, 21, 20, 22, 21, 20, 22, 21, 20],
    "Department": [
        "CSE", "CSE", "ECE", "CSE", "ME", "ECE",
        "CSE", "ME", "ECE", "CSE", "ME", "ECE"
    ],
    "Attendance": [92, 85, 78, 95, 65, 88, 72, 91, 80, 96, 68, 87],
    "StudyHours": [5, 4, 3, 6, 2, 5, 3, 6, 4, 7, 2, 5],
    "Assignments": [8, 7, 6, 9, 5, 8, 7, 9, 7, 10, 5, 8],
    "Midterm": [78, 72, 65, 88, 55, 76, 62, 85, 70, 90, 58, 75],
    "Final": [85, 80, 70, 92, 60, 84, 68, 90, 75, 95, 62, 82],
    "Placement": [
        "Yes", "Yes", "No", "Yes", "No", "Yes",
        "No", "Yes", "Yes", "Yes", "No", "Yes"
    ]
}

In [ ]:
df=pd.DataFrame(data_dict)

In [ ]:
df.head()

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5,8,78,85,Yes
1,Diya,Female,21,CSE,85,4,7,72,80,Yes
2,Rahul,Male,20,ECE,78,3,6,65,70,No
3,Priya,Female,22,CSE,95,6,9,88,92,Yes
4,Arjun,Male,21,ME,65,2,5,55,60,No

In [ ]:
df["Attendance"].mean()

np.float64(83.08333333333333)

In [ ]:
df[df["Attendance"]>df["Attendance"].mean()]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5,8,78,85,Yes
1,Diya,Female,21,CSE,85,4,7,72,80,Yes
3,Priya,Female,22,CSE,95,6,9,88,92,Yes
5,Sneha,Female,20,ECE,88,5,8,76,84,Yes
7,Ananya,Female,21,ME,91,6,9,85,90,Yes
9,Meera,Female,22,CSE,96,7,10,90,95,Yes
11,Isha,Female,20,ECE,87,5,8,75,82,Yes

In [ ]:
df[df["Attendance"]>75]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5,8,78,85,Yes
1,Diya,Female,21,CSE,85,4,7,72,80,Yes
2,Rahul,Male,20,ECE,78,3,6,65,70,No
3,Priya,Female,22,CSE,95,6,9,88,92,Yes
5,Sneha,Female,20,ECE,88,5,8,76,84,Yes
7,Ananya,Female,21,ME,91,6,9,85,90,Yes
8,Vikram,Male,20,ECE,80,4,7,70,75,Yes
9,Meera,Female,22,CSE,96,7,10,90,95,Yes
11,Isha,Female,20,ECE,87,5,8,75,82,Yes

In [ ]:
df[df["StudyHours"]>5]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
3,Priya,Female,22,CSE,95,6,9,88,92,Yes
7,Ananya,Female,21,ME,91,6,9,85,90,Yes
9,Meera,Female,22,CSE,96,7,10,90,95,Yes

.loc

In [ ]:
df.head()

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5,8,78,85,Yes
1,Diya,Female,21,CSE,85,4,7,72,80,Yes
2,Rahul,Male,20,ECE,78,3,6,65,70,No
3,Priya,Female,22,CSE,95,6,9,88,92,Yes
4,Arjun,Male,21,ME,65,2,5,55,60,No

In [ ]:
df.loc[4]

Name           Arjun
Gender          Male
Age               21
Department        ME
Attendance        65
StudyHours         2
Assignments        5
Midterm           55
Final             60
Placement         No
Name: 4, dtype: object

In [ ]:
df.loc[[4,5]]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
4,Arjun,Male,21,ME,65,2,5,55,60,No
5,Sneha,Female,20,ECE,88,5,8,76,84,Yes

In [ ]:
df.loc[5:]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
5,Sneha,Female,20,ECE,88,5,8,76,84,Yes
6,Karan,Male,22,CSE,72,3,7,62,68,No
7,Ananya,Female,21,ME,91,6,9,85,90,Yes
8,Vikram,Male,20,ECE,80,4,7,70,75,Yes
9,Meera,Female,22,CSE,96,7,10,90,95,Yes
10,Rohan,Male,21,ME,68,2,5,58,62,No
11,Isha,Female,20,ECE,87,5,8,75,82,Yes

In [ ]:
df.loc[5,"Department"]

'ECE'

In [ ]:
df.loc[10,"Assignments"]

np.int64(5)

In [ ]:
print(df.loc[10,"Midterm"])
print(df.loc[10,"Final"])
print(df.loc[10,"Midterm"])

58
62
58

In [ ]:
df.loc[2, "StudyHours"] = None

In [ ]:
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80,Yes
2,Rahul,Male,20,ECE,78,NaN,6,65,70,No
3,Priya,Female,22,CSE,95,6.0,9,88,92,Yes
4,Arjun,Male,21,ME,65,2.0,5,55,60,No
5,Sneha,Female,20,ECE,88,5.0,8,76,84,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68,No
7,Ananya,Female,21,ME,91,6.0,9,85,90,Yes
8,Vikram,Male,20,ECE,80,4.0,7,70,75,Yes
9,Meera,Female,22,CSE,96,7.0,10,90,95,Yes
10,Rohan,Male,21,ME,68,2.0,5,58,62,No
11,Isha,Female,20,ECE,87,5.0,8,75,82,Yes

In [ ]:
df.loc[9, "Final"] = None

In [ ]:
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80.0,Yes
2,Rahul,Male,20,ECE,78,NaN,6,65,70.0,No
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
4,Arjun,Male,21,ME,65,2.0,5,55,60.0,No
5,Sneha,Female,20,ECE,88,5.0,8,76,84.0,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68.0,No
7,Ananya,Female,21,ME,91,6.0,9,85,90.0,Yes
8,Vikram,Male,20,ECE,80,4.0,7,70,75.0,Yes
9,Meera,Female,22,CSE,96,7.0,10,90,NaN,Yes
10,Rohan,Male,21,ME,68,2.0,5,58,62.0,No
11,Isha,Female,20,ECE,87,5.0,8,75,82.0,Yes

In [ ]:
df.loc[9, "Name"] = "Advika"

In [ ]:
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80.0,Yes
2,Rahul,Male,20,ECE,78,NaN,6,65,70.0,No
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
4,Arjun,Male,21,ME,65,2.0,5,55,60.0,No
5,Sneha,Female,20,ECE,88,5.0,8,76,84.0,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68.0,No
7,Ananya,Female,21,ME,91,6.0,9,85,90.0,Yes
8,Vikram,Male,20,ECE,80,4.0,7,70,75.0,Yes
9,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes
10,Rohan,Male,21,ME,68,2.0,5,58,62.0,No
11,Isha,Female,20,ECE,87,5.0,8,75,82.0,Yes

In [ ]:
df.iloc[[9]]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
9,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes

In [ ]:
df = pd.concat([df, df.iloc[[9]]], ignore_index=True)

In [ ]:
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80.0,Yes
2,Rahul,Male,20,ECE,78,NaN,6,65,70.0,No
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
4,Arjun,Male,21,ME,65,2.0,5,55,60.0,No
5,Sneha,Female,20,ECE,88,5.0,8,76,84.0,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68.0,No
7,Ananya,Female,21,ME,91,6.0,9,85,90.0,Yes
8,Vikram,Male,20,ECE,80,4.0,7,70,75.0,Yes
9,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes
10,Rohan,Male,21,ME,68,2.0,5,58,62.0,No
11,Isha,Female,20,ECE,87,5.0,8,75,82.0,Yes
12,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes

In [ ]:
df.loc[9, "Name"] = "Meera"

In [ ]:
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80.0,Yes
2,Rahul,Male,20,ECE,78,NaN,6,65,70.0,No
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
4,Arjun,Male,21,ME,65,2.0,5,55,60.0,No
5,Sneha,Female,20,ECE,88,5.0,8,76,84.0,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68.0,No
7,Ananya,Female,21,ME,91,6.0,9,85,90.0,Yes
8,Vikram,Male,20,ECE,80,4.0,7,70,75.0,Yes
9,Meera,Female,22,CSE,96,7.0,10,90,NaN,Yes
10,Rohan,Male,21,ME,68,2.0,5,58,62.0,No
11,Isha,Female,20,ECE,87,5.0,8,75,82.0,Yes
12,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes

In [ ]:
df.isnull().sum()

Name           0
Gender         0
Age            0
Department     0
Attendance     0
StudyHours     1
Assignments    0
Midterm        0
Final          2
Placement      0
dtype: int64

In [ ]:
df.dtypes

Name               str
Gender             str
Age              int64
Department         str
Attendance       int64
StudyHours     float64
Assignments      int64
Midterm          int64
Final          float64
Placement          str
dtype: object

In [ ]:
df[df["Department"]=="CSE"]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
1,Diya,Female,21,CSE,85,4.0,7,72,80.0,Yes
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
6,Karan,Male,22,CSE,72,3.0,7,62,68.0,No
9,Meera,Female,22,CSE,96,7.0,10,90,NaN,Yes
12,Advika,Female,22,CSE,96,7.0,10,90,NaN,Yes

In [ ]:
df[(df["Attendance"]>75) & (df["Final"]>80)]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes
5,Sneha,Female,20,ECE,88,5.0,8,76,84.0,Yes
7,Ananya,Female,21,ME,91,6.0,9,85,90.0,Yes
11,Isha,Female,20,ECE,87,5.0,8,75,82.0,Yes

In [ ]:
df[(df["Department"]=="CSE") & (df["Final"]>=85)]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92,5.0,8,78,85.0,Yes
3,Priya,Female,22,CSE,95,6.0,9,88,92.0,Yes

In [ ]:
df.loc[2,"Final"]=None
df.loc[10,"Attendance"]=None
df.loc[10,"Assignments"]=None
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.0,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.0,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.0,NaN,6.0,65,NaN,No
3,Priya,Female,22,CSE,95.0,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.0,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.0,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.0,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.0,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.0,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes
10,Rohan,Male,21,ME,NaN,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.0,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes

In [ ]:
df.isnull().sum()

Name           0
Gender         0
Age            0
Department     0
Attendance     1
StudyHours     1
Assignments    1
Midterm        0
Final          3
Placement      0
dtype: int64

In [ ]:
print(df.shape)
df.drop_duplicates()

(13, 10)

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.0,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.0,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.0,NaN,6.0,65,NaN,No
3,Priya,Female,22,CSE,95.0,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.0,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.0,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.0,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.0,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.0,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes
10,Rohan,Male,21,ME,NaN,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.0,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes

In [ ]:
print(df.shape)

(13, 10)

In [ ]:
df.loc[[7]]

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
7,Ananya,Female,21,ME,91.0,6.0,9.0,85,90.0,Yes

In [ ]:
duplicate_df=pd.concat([df,df.loc[[7]]],ignore_index=True)
duplicate_df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.0,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.0,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.0,NaN,6.0,65,NaN,No
3,Priya,Female,22,CSE,95.0,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.0,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.0,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.0,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.0,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.0,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes
10,Rohan,Male,21,ME,NaN,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.0,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.0,7.0,10.0,90,NaN,Yes
13,Ananya,Female,21,ME,91.0,6.0,9.0,85,90.0,Yes

Calculate the percentage of missing values:

In [ ]:
df.isnull().sum()

Name           0
Gender         0
Age            0
Department     0
Attendance     1
StudyHours     1
Assignments    1
Midterm        0
Final          3
Placement      0
dtype: int64

In [ ]:
df.isnull().mean() * 100

Name            0.000000
Gender          0.000000
Age             0.000000
Department      0.000000
Attendance      7.692308
StudyHours      7.692308
Assignments     7.692308
Midterm         0.000000
Final          23.076923
Placement       0.000000
dtype: float64

Handling Missing Values

In [ ]:
df["Attendance"].mean()

np.float64(85.41666666666667)

In [ ]:
df["Attendance"]=df["Attendance"].fillna(df["Attendance"].mean(),inplace=True)
df

C:\Users\Arjun Singh\AppData\Local\Temp\ipykernel_23792\3342906491.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Attendance"]=df["Attendance"].fillna(df["Attendance"].mean(),inplace=True)

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.000000,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.000000,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.000000,NaN,6.0,65,NaN,No
3,Priya,Female,22,CSE,95.000000,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.000000,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.000000,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.000000,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.000000,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.000000,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.000000,7.0,10.0,90,NaN,Yes
10,Rohan,Male,21,ME,85.416667,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.000000,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.000000,7.0,10.0,90,NaN,Yes

In [ ]:
df["Final"]=df["Final"].fillna(df["Final"].max(),inplace=True)
df

C:\Users\Arjun Singh\AppData\Local\Temp\ipykernel_23792\706972356.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Final"]=df["Final"].fillna(df["Final"].max(),inplace=True)

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.000000,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.000000,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.000000,NaN,6.0,65,92.0,No
3,Priya,Female,22,CSE,95.000000,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.000000,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.000000,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.000000,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.000000,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.000000,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes
10,Rohan,Male,21,ME,85.416667,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.000000,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes

In [ ]:
df["Final"]=df["Final"].fillna(df["Final"].min())
df["Attendance"]=df["Attendance"].fillna(df["Attendance"].min())
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement
0,Aarav,Male,20,CSE,92.000000,5.0,8.0,78,85.0,Yes
1,Diya,Female,21,CSE,85.000000,4.0,7.0,72,80.0,Yes
2,Rahul,Male,20,ECE,78.000000,NaN,6.0,65,92.0,No
3,Priya,Female,22,CSE,95.000000,6.0,9.0,88,92.0,Yes
4,Arjun,Male,21,ME,65.000000,2.0,5.0,55,60.0,No
5,Sneha,Female,20,ECE,88.000000,5.0,8.0,76,84.0,Yes
6,Karan,Male,22,CSE,72.000000,3.0,7.0,62,68.0,No
7,Ananya,Female,21,ME,91.000000,6.0,9.0,85,90.0,Yes
8,Vikram,Male,20,ECE,80.000000,4.0,7.0,70,75.0,Yes
9,Meera,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes
10,Rohan,Male,21,ME,85.416667,2.0,NaN,58,62.0,No
11,Isha,Female,20,ECE,87.000000,5.0,8.0,75,82.0,Yes
12,Advika,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes

In [ ]:
df2=df[["Name","Gender","Final"]].copy()
df2

      Name  Gender  Final
0    Aarav    Male   85.0
1     Diya  Female   80.0
2    Rahul    Male   92.0
3    Priya  Female   92.0
4    Arjun    Male   60.0
5    Sneha  Female   84.0
6    Karan    Male   68.0
7   Ananya  Female   90.0
8   Vikram    Male   75.0
9    Meera  Female   92.0
10   Rohan    Male   62.0
11    Isha  Female   82.0
12  Advika  Female   92.0

In [ ]:
df2.loc[4:]

      Name  Gender  Final
4    Arjun    Male   60.0
5    Sneha  Female   84.0
6    Karan    Male   68.0
7   Ananya  Female   90.0
8   Vikram    Male   75.0
9    Meera  Female   92.0
10   Rohan    Male   62.0
11    Isha  Female   82.0
12  Advika  Female   92.0

In [ ]:
df2.loc[:5]

    Name  Gender  Final
0  Aarav    Male   85.0
1   Diya  Female   80.0
2  Rahul    Male   92.0
3  Priya  Female   92.0
4  Arjun    Male   60.0
5  Sneha  Female   84.0

In [ ]:
df2.loc[1:5]

    Name  Gender  Final
1   Diya  Female   80.0
2  Rahul    Male   92.0
3  Priya  Female   92.0
4  Arjun    Male   60.0
5  Sneha  Female   84.0

In [ ]:
df["TotalMarks"] = df["Midterm"] + df["Final"]
df

,Name,Gender,Age,Department,Attendance,StudyHours,Assignments,Midterm,Final,Placement,TotalMarks
0,Aarav,Male,20,CSE,92.000000,5.0,8.0,78,85.0,Yes,163.0
1,Diya,Female,21,CSE,85.000000,4.0,7.0,72,80.0,Yes,152.0
2,Rahul,Male,20,ECE,78.000000,NaN,6.0,65,92.0,No,157.0
3,Priya,Female,22,CSE,95.000000,6.0,9.0,88,92.0,Yes,180.0
4,Arjun,Male,21,ME,65.000000,2.0,5.0,55,60.0,No,115.0
5,Sneha,Female,20,ECE,88.000000,5.0,8.0,76,84.0,Yes,160.0
6,Karan,Male,22,CSE,72.000000,3.0,7.0,62,68.0,No,130.0
7,Ananya,Female,21,ME,91.000000,6.0,9.0,85,90.0,Yes,175.0
8,Vikram,Male,20,ECE,80.000000,4.0,7.0,70,75.0,Yes,145.0
9,Meera,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes,182.0
10,Rohan,Male,21,ME,85.416667,2.0,NaN,58,62.0,No,120.0
11,Isha,Female,20,ECE,87.000000,5.0,8.0,75,82.0,Yes,157.0
12,Advika,Female,22,CSE,96.000000,7.0,10.0,90,92.0,Yes,182.0