<a href="https://colab.research.google.com/github/007arjungangwar/Foundations-of-Data-Engineering-Sec2/blob/main/Fetching_Data_From_an_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import requests

In [44]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [45]:
response

In [46]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qPNG2riEQLBknaa20RhUCr8QtWA.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 231.0192,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.322,
   'vote_count': 659},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 24.28,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.941,
   'vote_count': 339},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 64.2663,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.89,
   'vote_count': 2052},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 75.4156,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.727,
   'vote_count': 30931},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 102.8294,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 3855},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 58.2728,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 23269},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 155.5042,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.656,
   'vote_count': 6763},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 180.3103,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.614,
   'vote_count': 1615},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 29.467,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 17687},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 36.6553,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 14123},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 30.425,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 10193},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 61.3967,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 36276},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 32.2931,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18630},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 14.5483,
   'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.507,
   'vote_count': 4607},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 35.3112,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19550},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 54.9695,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 26992},
  {'adult': False,
   'backdrop_path': '/9sIqW8t1Owz2CSfJbQlmMO5rkFM.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 31.4861,
   'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.499,
   'vote_count': 1073},
  {'adult': False,
   'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 42.2446,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.489,
   'vote_count': 21004},
  {'adult': False,
   'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 73.9896,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.483,
   'vote_count': 40605},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 27.9,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-07-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.483,
   'vote_count': 12782}],
 'total_pages': 553,
 'total_results': 11059}

In [19]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/qPNG2riEQLBknaa20RhUCr8QtWA.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 231.0192,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.322,
  'vote_count': 659},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 24.28,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.941,
  'vote_count': 339},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 64.2663,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.89,
  'vote_count': 2052},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 75.4156,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.727,
  'vote_count': 30931},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 102.8294,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.7,
  'vote_count': 3855},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 58.2728,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.7,
  'vote_count': 23269},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 155.5042,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.656,
  'vote_count': 6763},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 180.3103,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.614,
  'vote_count': 1615},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 29.467,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17687},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 36.6553,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 14123},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 30.425,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 10193},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 61.3967,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 36276},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 32.2931,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 18630},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 14.5483,
  'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.507,
  'vote_count': 4607},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 35.3112,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19550},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 54.9695,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26992},
 {'adult': False,
  'backdrop_path': '/9sIqW8t1Owz2CSfJbQlmMO5rkFM.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 31.4861,
  'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.499,
  'vote_count': 1073},
 {'adult': False,
  'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 42.2446,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.489,
  'vote_count': 21004},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 73.9896,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.483,
  'vote_count': 40605},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 27.9,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.483,
  'vote_count': 12782}]

In [47]:
temp_df2 = pd.DataFrame(response.json()['results'])
temp_df2.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qPNG2riEQLBknaa20RhUCr8QtWA.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",231.0192,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.322,659
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.2800,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.941,339
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",64.2663,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.890,2052
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,75.4156,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,30931
4,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",102.8294,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.700,3855

In [20]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [21]:
temp_df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.322,659
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.890,2052
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30931
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.700,3855
5,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,58.2728,8.700,23269
6,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,155.5042,8.656,6763
7,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,180.3103,8.614,1615
8,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,29.4670,8.570,17687
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,36.6553,8.600,14123
10,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,30.4250,8.600,10193
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,61.3967,8.534,36276
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.2931,8.534,18630
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.5483,8.507,4607
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,35.3112,8.506,19550
15,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,54.9695,8.500,26992
16,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,31.4861,8.499,1073
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,42.2446,8.489,21004
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,73.9896,8.483,40605
19,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,27.9000,8.483,12782

In [22]:
temp_df.shape

(20, 7)

In [5]:
df = pd.DataFrame()

In [6]:
df.head()

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,554):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [48]:
for i in range(1,554):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    data = response.json()
    if 'results' not in data or not data['results']:
        print(f"No more results or error for page {i}. Continue loop.")
        continue
    temp_df = pd.DataFrame(data['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

No more results or error for page 501. Continue loop.
No more results or error for page 502. Continue loop.
No more results or error for page 503. Continue loop.
No more results or error for page 504. Continue loop.
No more results or error for page 505. Continue loop.
No more results or error for page 506. Continue loop.
No more results or error for page 507. Continue loop.
No more results or error for page 508. Continue loop.
No more results or error for page 509. Continue loop.
No more results or error for page 510. Continue loop.
No more results or error for page 511. Continue loop.
No more results or error for page 512. Continue loop.
No more results or error for page 513. Continue loop.
No more results or error for page 514. Continue loop.
No more results or error for page 515. Continue loop.
No more results or error for page 516. Continue loop.
No more results or error for page 517. Continue loop.
No more results or error for page 518. Continue loop.
No more results or error for page 519. Continue loop.
No more results or error for page 520. Continue loop.
No more results or error for page 521. Continue loop.
No more results or error for page 522. Continue loop.
No more results or error for page 523. Continue loop.
No more results or error for page 524. Continue loop.
No more results or error for page 525. Continue loop.
No more results or error for page 526. Continue loop.
No more results or error for page 527. Continue loop.
No more results or error for page 528. Continue loop.
No more results or error for page 529. Continue loop.
No more results or error for page 530. Continue loop.
No more results or error for page 531. Continue loop.
No more results or error for page 532. Continue loop.
No more results or error for page 533. Continue loop.
No more results or error for page 534. Continue loop.
No more results or error for page 535. Continue loop.
No more results or error for page 536. Continue loop.
No more results or error for page 537. Continue loop.
No more results or error for page 538. Continue loop.
No more results or error for page 539. Continue loop.
No more results or error for page 540. Continue loop.
No more results or error for page 541. Continue loop.
No more results or error for page 542. Continue loop.
No more results or error for page 543. Continue loop.
No more results or error for page 544. Continue loop.
No more results or error for page 545. Continue loop.
No more results or error for page 546. Continue loop.
No more results or error for page 547. Continue loop.
No more results or error for page 548. Continue loop.
No more results or error for page 549. Continue loop.
No more results or error for page 550. Continue loop.
No more results or error for page 551. Continue loop.
No more results or error for page 552. Continue loop.
No more results or error for page 553. Continue loop.

In [49]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.322,659
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.890,2052
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30931
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.700,3855
...,...,...,...,...,...,...,...
38555,354287,War Machine,A rock star general bent on winning the “impos...,2017-05-26,6.0336,5.615,1253
38556,19912,The Final Destination,A horrifying premonition saves a young man and...,2009-08-26,10.2554,5.614,3974
38557,18998,Darkman II: The Return of Durant,Darkman and Durant return and they hate each o...,1995-07-11,2.4929,5.600,304
38558,10329,Congo,Eight people embark on an expedition into the ...,1995-06-09,5.2810,5.614,1005
38559,523931,Megalodon,A military vessel on the search for an unident...,2018-08-10,3.4531,5.613,322

In [50]:
df.shape

(38560, 7)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38560 entries, 0 to 38559
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            38560 non-null  int64
 1   title         38560 non-null  object
 2   overview      38560 non-null  object
 3   release_date  38560 non-null  object
 4   popularity    38560 non-null  float64
 5   vote_average  38560 non-null  float64
 6   vote_count    38560 non-null  int64
dtypes: float64(2), int64(2), object(3)
memory usage: 2.1+ MB

In [23]:
df.to_csv('Tmdb_top_Listed_movies.csv')

# imdb/top-rated-english-movies

In [39]:
import requests

url = "https://imdb236.p.rapidapi.com/api/imdb/cast/nm0000190/titles"

headers = {
    "x-rapidapi-host": "imdb236.p.rapidapi.com",
    "x-rapidapi-key": "0eb7097e7fmsh51f08c47a5e06e1p1fcb3djsnb6eb69eac7d"
}

response = requests.get(url, headers=headers)
data = response.json()

In [40]:
data

{'message': 'You are not subscribed to this API.'}

In [37]:
import requests

headers = {
    "x-rapidapi-host": "imdb236.p.rapidapi.com",
    "x-rapidapi-key": "0eb7097e7fmsh51f08c47a5e06e1p1fcb3djsnb6eb69eac7d"
}
response = requests.get(
    "https://imdb236.p.rapidapi.com/api/imdb/cast/nm0000190/titles",
    headers=headers
)

In [38]:
response

# Python (Requests)

In [1]:
import requests

url = "https://imdb236.p.rapidapi.com/api/imdb/cast/nm0000190/titles"
headers = {
    "X-Rapidapi-Key": "0eb7097e7fmsh51f08c47a5e06e1p1fcb3djsnb6eb69eac7da",
    "X-Rapidapi-Host": "imdb236.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
print(response.json())

[{'id': 'tt41059410', 'url': 'https://www.imdb.com/title/tt41059410/', 'primaryTitle': 'Bear Grylls Is Running Wild', 'originalTitle': 'Bear Grylls Is Running Wild', 'type': 'tvSeries', 'description': 'Bear Grylls guides celebrities through extreme global locations from Norwegian glaciers to Welsh mountains. Adventures include Arctic rainforest, canyonlands, desert terrain, glacier crossings, canyon descents, and an 11,000-foot freefall.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2026-04-21', 'startYear': 2026, 'endYear': None, 'runtimeMinutes': None, 'genres': None, 'interests': None, 'countriesOfOrigin': None, 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [{'id': 'co0767763', 'name': 'Propagate Content'}, {'id': 'co0846243', 'name': 'The Natural Studios'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.4, 'numVotes': 78, 'metascore': None}, {'id': 'tt6773088', 'url': 'https://www.imdb.com/title/tt6773088/', 'primaryTitle': 'Brothers', 'originalTitle': 'Brothers', 'type': 'tvSeries', 'description': 'It follows McConaughey and Harrelson as they try to live together on a Texas ranch. That close space puts their friendship to the test.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2026-09-23', 'startYear': 2026, 'endYear': None, 'runtimeMinutes': None, 'genres': ['Comedy'], 'interests': ['Comedy'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Austin, Texas, USA'], 'productionCompanies': [{'id': 'co0861654', 'name': 'Apple Studios'}, {'id': 'co0781350', 'name': 'Paramount Television Studios'}, {'id': 'co0562101', 'name': 'Skydance Television'}], 'budget': None, 'grossWorldwide': None, 'averageRating': None, 'numVotes': None, 'metascore': None}, {'id': 'tt21103218', 'url': 'https://www.imdb.com/title/tt21103218/', 'primaryTitle': 'The Lost Bus', 'originalTitle': 'The Lost Bus', 'type': 'movie', 'description': 'A wayward school bus driver and a dedicated school teacher battle to save 22 children from a terrifying inferno.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'R', 'isAdult': False, 'releaseDate': '2025-10-03', 'startYear': 2025, 'endYear': None, 'runtimeMinutes': 130, 'genres': ['Biography', 'Drama', 'History'], 'interests': ['Disaster', 'Biography', 'Drama', 'History', 'Thriller'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Ruidoso, New Mexico, USA'], 'productionCompanies': [{'id': 'co0822606', 'name': 'Apple Original Films'}, {'id': 'co0098315', 'name': 'Blumhouse Productions'}, {'id': 'co0032319', 'name': 'Comet Pictures'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.8, 'numVotes': 55730, 'metascore': 64}, {'id': 'tt27706593', 'url': 'https://www.imdb.com/title/tt27706593/', 'primaryTitle': 'The Rivals of Amziah King', 'originalTitle': 'The Rivals of Amziah King', 'type': 'movie', 'description': 'Amziah King, beekeeper, musician, and anchor of his community, reunites with former foster daughter Kateri after many years apart, and fends off threats to his honey business.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2025-08-21', 'startYear': 2025, 'endYear': None, 'runtimeMinutes': 130, 'genres': ['Crime', 'Drama', 'Thriller'], 'interests': ['Caper', 'Contemporary Western', 'Crime', 'Drama', 'Thriller'], 'countriesOfOrigin': ['US', 'GB'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Jasper, Alabama, USA'], 'productionCompanies': [{'id': 'co1031934', 'name': 'Black Bear'}, {'id': 'co0159772', 'name': 'Heyday Films'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 7.8, 'numVotes': 329, 'metascore': 65}, {'id': 'tt31937790', 'url': 'https://www.imdb.com/title/tt31937790/', 'primaryTitle': 'Superhuman Body: World of Medical Marvels', 'originalTitle': 'Superhuman Body: World of Medical Marvels', 'type': 'movie', 'description': 'Explores the work of scientists and bioengineers who are behind groundbreaking medical innovations, such as CAR T-cell immunotherapy and the inner workings of the human body for treating blood cancers like leukemia.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=YaJEpU7fkqA', 'contentRating': None, 'isAdult': False, 'releaseDate': '2024-04-12', 'startYear': 2024, 'endYear': None, 'runtimeMinutes': 40, 'genres': ['Documentary'], 'interests': ['Documentary'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [{'id': 'co0053632', 'name': 'MacGillivray Freeman Films'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.9, 'numVotes': 25, 'metascore': None}, {'id': 'tt27590028', 'url': 'https://www.imdb.com/title/tt27590028/', 'primaryTitle': 'The Oscars', 'originalTitle': 'The Oscars', 'type': 'tvSpecial', 'description': 'The 96th Academy Awards, held on March 10th, 2024 from the Dolby Threatre in Hollywood and hosted by comedian Jimmy Kimmel for the fourth time. The cultural phenomenon of "Barbenheimer" in six different categories is a recurring theme.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-14', 'isAdult': False, 'releaseDate': '2024-03-10', 'startYear': 2024, 'endYear': None, 'runtimeMinutes': 157, 'genres': ['Comedy', 'Music'], 'interests': ['Comedy', 'Music', 'Reality TV'], 'countriesOfOrigin': None, 'externalLinks': None, 'spokenLanguages': ['en', 'es'], 'filmingLocations': ['Dolby Theatre, Hollywood, California, USA'], 'productionCompanies': [{'id': 'co0104239', 'name': 'Done and Dusted Productions'}, {'id': 'co0772531', 'name': 'Raj Kapoor Productions'}, {'id': 'co0050231', 'name': 'Academy of Motion Picture Arts and Sciences (AMPAS)'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.6, 'numVotes': 1634, 'metascore': None}, {'id': 'tt29580199', 'url': 'https://www.imdb.com/title/tt29580199/', 'primaryTitle': 'Unsolved Mysteries: Behind the Legacy', 'originalTitle': 'Unsolved Mysteries: Behind the Legacy', 'type': 'movie', 'description': 'A tribute to the iconic series that shaped future generations of true crime TV, featuring interviews with the creators and exclusive behind-the-scenes footage.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2023-10-05', 'startYear': 2023, 'endYear': None, 'runtimeMinutes': 55, 'genres': ['Reality-TV'], 'interests': ['Reality TV'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://filmrise.com/film/unsolved-mysteries-behind-the-legacy', 'https://unsolved.com/behind-the-legacy/'], 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [], 'budget': None, 'grossWorldwide': None, 'averageRating': 7.4, 'numVotes': 114, 'metascore': None}, {'id': 'tt23219702', 'url': 'https://www.imdb.com/title/tt23219702/', 'primaryTitle': '2023 CMT Music Awards', 'originalTitle': '2023 CMT Music Awards', 'type': 'tvSpecial', 'description': "The 2023 CMT MUSIC AWARDS, country music's only fan-voted awards show", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-PG', 'isAdult': False, 'releaseDate': '2023-04-02', 'startYear': 2023, 'endYear': None, 'runtimeMinutes': 132, 'genres': ['Music'], 'interests': ['Music'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Moody Center, Austin, Texas, USA'], 'productionCompanies': [{'id': 'co0744878', 'name': 'Switched on Entertainment'}, {'id': 'co0084871', 'name': 'CMT'}, {'id': 'co0321734', 'name': '4Wall Entertainment'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 5.9, 'numVotes': 64, 'metascore': None}, {'id': 'tt10814036', 'url': 'https://www.imdb.com/title/tt10814036/', 'primaryTitle': 'Agent Elvis', 'originalTitle': 'Agent Elvis', 'type': 'tvSeries', 'description': 'Elvis trades in his jumpsuit for a jetpack when he joins a secret government spy program to help battle the dark forces that threaten the country.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-MA', 'isAdult': False, 'releaseDate': '2023-03-17', 'startYear': 2023, 'endYear': 2023, 'runtimeMinutes': None, 'genres': ['Action', 'Animation', 'Comedy'], 'interests': ['Adult Animation', 'Action', 'Animation', 'Comedy', 'Crime', 'Thriller'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.netflix.com/title/80240585/'], 'spokenLanguages': ['en'], 'filmingLocations': ['Las Vegas, Nevada, USA'], 'productionCompanies': [{'id': 'co0086397', 'name': 'Sony Pictures Television'}, {'id': 'co0121181', 'name': 'Sony Pictures Animation'}, {'id': 'co0186051', 'name': 'Titmouse'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.8, 'numVotes': 2953, 'metascore': None}, {'id': 'tt18967390', 'url': 'https://www.imdb.com/title/tt18967390/', 'primaryTitle': 'Deep in the Heart: A Texas Wildlife Story', 'originalTitle': 'Deep in the Heart: A Texas Wildlife Story', 'type': 'movie', 'description': 'A visually stunning celebration of what makes Texas unique, its diverse landscapes and remarkable wildlife behavior that cannot be found anywhere else in the world.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=GNZ71xjAE0U', 'contentRating': 'PG', 'isAdult': False, 'releaseDate': '2022-06-03', 'startYear': 2022, 'endYear': None, 'runtimeMinutes': 101, 'genres': ['Documentary'], 'interests': ['Nature Documentary', 'Documentary'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.deepintheheartwildlife.com/'], 'spokenLanguages': ['en'], 'filmingLocations': ['Texas, USA'], 'productionCompanies': [{'id': 'co0797683', 'name': 'Fin & Fur Films'}], 'budget': None, 'grossWorldwide': 480240, 'averageRating': 7.6, 'numVotes': 286, 'metascore': None}, {'id': 'tt14477048', 'url': 'https://www.imdb.com/title/tt14477048/', 'primaryTitle': 'Oscars: Into the Spotlight', 'originalTitle': 'Oscars: Into the Spotlight', 'type': 'tvSpecial', 'description': None, 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2021-04-25', 'startYear': 2021, 'endYear': None, 'runtimeMinutes': None, 'genres': None, 'interests': None, 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Union Station - 800 N. Alameda Street, Downtown, Los Angeles, California, USA'], 'productionCompanies': [{'id': 'co0050231', 'name': 'Academy of Motion Picture Arts and Sciences (AMPAS)'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 5.6, 'numVotes': 29, 'metascore': None}, {'id': 'tt13819950', 'url': 'https://www.imdb.com/title/tt13819950/', 'primaryTitle': "Stephen A's World", 'originalTitle': "Stephen A's World", 'type': 'tvSeries', 'description': "ESPN commentator Stephen A. Smith hosts this new show featuring his unfiltered take on all the day's biggest sports stories.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2021-01-11', 'startYear': 2021, 'endYear': None, 'runtimeMinutes': None, 'genres': ['Sport', 'Talk-Show'], 'interests': ['Sport', 'Talk Show'], 'countriesOfOrigin': None, 'externalLinks': ['https://espn.com/'], 'spokenLanguages': None, 'filmingLocations': ['New York City, New York, USA'], 'productionCompanies': [{'id': 'co0185451', 'name': 'ESPN Enterprises'}, {'id': 'co0756519', 'name': 'ESPN'}, {'id': 'co0044374', 'name': 'The Walt Disney Company'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 4.7, 'numVotes': 42, 'metascore': None}, {'id': 'tt12688170', 'url': 'https://www.imdb.com/title/tt12688170/', 'primaryTitle': 'The Kids Tonight Show', 'originalTitle': 'The Kids Tonight Show', 'type': 'tvSeries', 'description': "Kids version of 'The Tonight Show'.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMGM4MWM1NmUtNmZhMi00ZDJkLTk4Y2EtZjAyMTNlYjA3MzM1XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMGM4MWM1NmUtNmZhMi00ZDJkLTk4Y2EtZjAyMTNlYjA3MzM1XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BM

In [54]:
import requests

response = requests.get('https://imdb236.p.rapidapi.com/api/imdb/cast/nm0000190/titles', headers={"X-Rapidapi-Key": "0eb7097e7fmsh51f08c47a5e06e1p1fcb3djsnb6eb69eac7da", "X-Rapidapi-Host": "imdb236.p.rapidapi.com"})
print(response.json())

[{'id': 'tt6773088', 'url': 'https://www.imdb.com/title/tt6773088/', 'primaryTitle': 'Brothers', 'originalTitle': 'Brothers', 'type': 'tvSeries', 'description': 'It follows McConaughey and Harrelson as they try to live together on a Texas ranch. That close space puts their friendship to the test.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVhNzc1ZjktMWY2ZC00OTQ2LTgwNzEtMTk4MDE5Njc3OGFlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2026-09-23', 'startYear': 2026, 'endYear': None, 'runtimeMinutes': None, 'genres': ['Comedy'], 'interests': ['Comedy'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Austin, Texas, USA'], 'productionCompanies': [{'id': 'co0861654', 'name': 'Apple Studios'}, {'id': 'co0781350', 'name': 'Paramount Television Studios'}, {'id': 'co0562101', 'name': 'Skydance Television'}], 'budget': None, 'grossWorldwide': None, 'averageRating': None, 'numVotes': None, 'metascore': None}, {'id': 'tt41059410', 'url': 'https://www.imdb.com/title/tt41059410/', 'primaryTitle': 'Bear Grylls Is Running Wild', 'originalTitle': 'Bear Grylls Is Running Wild', 'type': 'tvSeries', 'description': 'Bear Grylls guides celebrities through extreme global locations from Norwegian glaciers to Welsh mountains. Adventures include Arctic rainforest, canyonlands, desert terrain, glacier crossings, canyon descents, and an 11,000-foot freefall.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMThjOTg3MDgtYzQxYy00ZjI5LWI5NWUtZjgwZWY2ZTQwYTVkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2026-04-21', 'startYear': 2026, 'endYear': None, 'runtimeMinutes': None, 'genres': None, 'interests': None, 'countriesOfOrigin': None, 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [{'id': 'co0767763', 'name': 'Propagate Content'}, {'id': 'co0846243', 'name': 'The Natural Studios'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.4, 'numVotes': 78, 'metascore': None}, {'id': 'tt21103218', 'url': 'https://www.imdb.com/title/tt21103218/', 'primaryTitle': 'The Lost Bus', 'originalTitle': 'The Lost Bus', 'type': 'movie', 'description': 'A wayward school bus driver and a dedicated school teacher battle to save 22 children from a terrifying inferno.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BZTIzNmQzYzUtNTdlNi00NmY5LThmNTYtMGFmZjUxMTgzOGNmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'R', 'isAdult': False, 'releaseDate': '2025-10-03', 'startYear': 2025, 'endYear': None, 'runtimeMinutes': 130, 'genres': ['Biography', 'Drama', 'History'], 'interests': ['Disaster', 'Biography', 'Drama', 'History', 'Thriller'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Ruidoso, New Mexico, USA'], 'productionCompanies': [{'id': 'co0822606', 'name': 'Apple Original Films'}, {'id': 'co0098315', 'name': 'Blumhouse Productions'}, {'id': 'co0032319', 'name': 'Comet Pictures'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.8, 'numVotes': 55730, 'metascore': 64}, {'id': 'tt27706593', 'url': 'https://www.imdb.com/title/tt27706593/', 'primaryTitle': 'The Rivals of Amziah King', 'originalTitle': 'The Rivals of Amziah King', 'type': 'movie', 'description': 'Amziah King, beekeeper, musician, and anchor of his community, reunites with former foster daughter Kateri after many years apart, and fends off threats to his honey business.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BOGVkMTY3OTMtMjEwOC00MGVmLTlmNmItZmZhNDNhYTEzOTQ0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2025-08-21', 'startYear': 2025, 'endYear': None, 'runtimeMinutes': 130, 'genres': ['Crime', 'Drama', 'Thriller'], 'interests': ['Caper', 'Contemporary Western', 'Crime', 'Drama', 'Thriller'], 'countriesOfOrigin': ['US', 'GB'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Jasper, Alabama, USA'], 'productionCompanies': [{'id': 'co1031934', 'name': 'Black Bear'}, {'id': 'co0159772', 'name': 'Heyday Films'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 7.8, 'numVotes': 329, 'metascore': 65}, {'id': 'tt31937790', 'url': 'https://www.imdb.com/title/tt31937790/', 'primaryTitle': 'Superhuman Body: World of Medical Marvels', 'originalTitle': 'Superhuman Body: World of Medical Marvels', 'type': 'movie', 'description': 'Explores the work of scientists and bioengineers who are behind groundbreaking medical innovations, such as CAR T-cell immunotherapy and the inner workings of the human body for treating blood cancers like leukemia.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzM4ZWEyZmUtNjg1YS00MDllLTk0MTUtNWU4ZGY0NjNiMmZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=YaJEpU7fkqA', 'contentRating': None, 'isAdult': False, 'releaseDate': '2024-04-12', 'startYear': 2024, 'endYear': None, 'runtimeMinutes': 40, 'genres': ['Documentary'], 'interests': ['Documentary'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [{'id': 'co0053632', 'name': 'MacGillivray Freeman Films'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.9, 'numVotes': 25, 'metascore': None}, {'id': 'tt27590028', 'url': 'https://www.imdb.com/title/tt27590028/', 'primaryTitle': 'The Oscars', 'originalTitle': 'The Oscars', 'type': 'tvSpecial', 'description': 'The 96th Academy Awards, held on March 10th, 2024 from the Dolby Threatre in Hollywood and hosted by comedian Jimmy Kimmel for the fourth time. The cultural phenomenon of "Barbenheimer" in six different categories is a recurring theme.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BOWQyNDA5NzYtODFlMi00MmQwLTlmYTMtYjI4NmYwYWNmMjYwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-14', 'isAdult': False, 'releaseDate': '2024-03-10', 'startYear': 2024, 'endYear': None, 'runtimeMinutes': 157, 'genres': ['Comedy', 'Music'], 'interests': ['Comedy', 'Music', 'Reality TV'], 'countriesOfOrigin': None, 'externalLinks': None, 'spokenLanguages': ['en', 'es'], 'filmingLocations': ['Dolby Theatre, Hollywood, California, USA'], 'productionCompanies': [{'id': 'co0104239', 'name': 'Done and Dusted Productions'}, {'id': 'co0772531', 'name': 'Raj Kapoor Productions'}, {'id': 'co0050231', 'name': 'Academy of Motion Picture Arts and Sciences (AMPAS)'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.6, 'numVotes': 1634, 'metascore': None}, {'id': 'tt29580199', 'url': 'https://www.imdb.com/title/tt29580199/', 'primaryTitle': 'Unsolved Mysteries: Behind the Legacy', 'originalTitle': 'Unsolved Mysteries: Behind the Legacy', 'type': 'movie', 'description': 'A tribute to the iconic series that shaped future generations of true crime TV, featuring interviews with the creators and exclusive behind-the-scenes footage.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWFkYTdkNmMtNGJlMS00ZWY1LWFmY2MtMjQxYTU1Y2FjZThiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2023-10-05', 'startYear': 2023, 'endYear': None, 'runtimeMinutes': 55, 'genres': ['Reality-TV'], 'interests': ['Reality TV'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://filmrise.com/film/unsolved-mysteries-behind-the-legacy', 'https://unsolved.com/behind-the-legacy/'], 'spokenLanguages': ['en'], 'filmingLocations': None, 'productionCompanies': [], 'budget': None, 'grossWorldwide': None, 'averageRating': 7.4, 'numVotes': 114, 'metascore': None}, {'id': 'tt23219702', 'url': 'https://www.imdb.com/title/tt23219702/', 'primaryTitle': '2023 CMT Music Awards', 'originalTitle': '2023 CMT Music Awards', 'type': 'tvSpecial', 'description': "The 2023 CMT MUSIC AWARDS, country music's only fan-voted awards show", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BN2UyZDY3MDctMDRmMi00ZGI4LThkM2UtY2YzMTRmNTZjMDVkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-PG', 'isAdult': False, 'releaseDate': '2023-04-02', 'startYear': 2023, 'endYear': None, 'runtimeMinutes': 132, 'genres': ['Music'], 'interests': ['Music'], 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Moody Center, Austin, Texas, USA'], 'productionCompanies': [{'id': 'co0744878', 'name': 'Switched on Entertainment'}, {'id': 'co0084871', 'name': 'CMT'}, {'id': 'co0321734', 'name': '4Wall Entertainment'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 5.9, 'numVotes': 64, 'metascore': None}, {'id': 'tt10814036', 'url': 'https://www.imdb.com/title/tt10814036/', 'primaryTitle': 'Agent Elvis', 'originalTitle': 'Agent Elvis', 'type': 'tvSeries', 'description': 'Elvis trades in his jumpsuit for a jetpack when he joins a secret government spy program to help battle the dark forces that threaten the country.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYzEyYWM4ZjYtMDQxOC00Mjg0LTg2MDYtYmI5Zjk5ZjNiNmM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': 'TV-MA', 'isAdult': False, 'releaseDate': '2023-03-17', 'startYear': 2023, 'endYear': 2023, 'runtimeMinutes': None, 'genres': ['Action', 'Animation', 'Comedy'], 'interests': ['Adult Animation', 'Action', 'Animation', 'Comedy', 'Crime', 'Thriller'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.netflix.com/title/80240585/'], 'spokenLanguages': ['en'], 'filmingLocations': ['Las Vegas, Nevada, USA'], 'productionCompanies': [{'id': 'co0086397', 'name': 'Sony Pictures Television'}, {'id': 'co0121181', 'name': 'Sony Pictures Animation'}, {'id': 'co0186051', 'name': 'Titmouse'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 6.8, 'numVotes': 2953, 'metascore': None}, {'id': 'tt18967390', 'url': 'https://www.imdb.com/title/tt18967390/', 'primaryTitle': 'Deep in the Heart: A Texas Wildlife Story', 'originalTitle': 'Deep in the Heart: A Texas Wildlife Story', 'type': 'movie', 'description': 'A visually stunning celebration of what makes Texas unique, its diverse landscapes and remarkable wildlife behavior that cannot be found anywhere else in the world.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BODgyN2Y2ZjItMDIyNy00YTZlLWE3MDItMmMzZmM0MmYxYWZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=GNZ71xjAE0U', 'contentRating': 'PG', 'isAdult': False, 'releaseDate': '2022-06-03', 'startYear': 2022, 'endYear': None, 'runtimeMinutes': 101, 'genres': ['Documentary'], 'interests': ['Nature Documentary', 'Documentary'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.deepintheheartwildlife.com/'], 'spokenLanguages': ['en'], 'filmingLocations': ['Texas, USA'], 'productionCompanies': [{'id': 'co0797683', 'name': 'Fin & Fur Films'}], 'budget': None, 'grossWorldwide': 480240, 'averageRating': 7.6, 'numVotes': 286, 'metascore': None}, {'id': 'tt14477048', 'url': 'https://www.imdb.com/title/tt14477048/', 'primaryTitle': 'Oscars: Into the Spotlight', 'originalTitle': 'Oscars: Into the Spotlight', 'type': 'tvSpecial', 'description': None, 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYWVkZWQ2ZTYtODFlMi00MDFmLWI5ODktMWVlNjhkZmFkNGY0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2021-04-25', 'startYear': 2021, 'endYear': None, 'runtimeMinutes': None, 'genres': None, 'interests': None, 'countriesOfOrigin': ['US'], 'externalLinks': None, 'spokenLanguages': ['en'], 'filmingLocations': ['Union Station - 800 N. Alameda Street, Downtown, Los Angeles, California, USA'], 'productionCompanies': [{'id': 'co0050231', 'name': 'Academy of Motion Picture Arts and Sciences (AMPAS)'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 5.6, 'numVotes': 29, 'metascore': None}, {'id': 'tt13819950', 'url': 'https://www.imdb.com/title/tt13819950/', 'primaryTitle': "Stephen A's World", 'originalTitle': "Stephen A's World", 'type': 'tvSeries', 'description': "ESPN commentator Stephen A. Smith hosts this new show featuring his unfiltered take on all the day's biggest sports stories.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTc1ZTcwYjItODFkMy00YzE2LWFlYTEtYjA0NGNmZjk3N2Q4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': None, 'contentRating': None, 'isAdult': False, 'releaseDate': '2021-01-11', 'startYear': 2021, 'endYear': None, 'runtimeMinutes': None, 'genres': ['Sport', 'Talk-Show'], 'interests': ['Sport', 'Talk Show'], 'countriesOfOrigin': None, 'externalLinks': ['https://espn.com/'], 'spokenLanguages': None, 'filmingLocations': ['New York City, New York, USA'], 'productionCompanies': [{'id': 'co0185451', 'name': 'ESPN Enterprises'}, {'id': 'co0756519', 'name': 'ESPN'}, {'id': 'co0044374', 'name': 'The Walt Disney Company'}], 'budget': None, 'grossWorldwide': None, 'averageRating': 4.7, 'numVotes': 42, 'metascore': None}, {'id': 'tt12688170', 'url': 'https://www.imdb.com/title/tt12688170/', 'primaryTitle': 'The Kids Tonight Show', 'originalTitle': 'The Kids Tonight Show', 'type': 'tvSeries', 'description': "Kids version of 'The Tonight Show'.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMGM4MWM1NmUtNmZhMi00ZDJkLTk4Y2EtZjAyMTNlYjA3MzM1XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMGM4MWM1NmUtNmZhMi00ZDJkLTk4Y2EtZjAyMTNlYjA3MzM1XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BM